name: Build & Deploy Angular Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/amerhashima/hismedfront:latest .

      - name: Push Image
        run: |
          docker push ghcr.io/amerhashima/hismedfront:latest

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/amerhashima/hismedfront:latest
            docker stop his-frontend || true
            docker rm his-frontend || true
            docker run -d \
              --name his-frontend \
              -p 4200:80 \
              --restart always \
              ghcr.io/amerhashima/hismedfront:latest
